### ISSUE TITLE
Invitation to move to testing-library org

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/pptr-testing-library#10]
It's up to you, but if you'd like, you're welcome to transfer this repository to the [testing-library organization on GitHub](https://github.com/testing-library). This will give your project more credibility as part of the testing-library family of projects with a unified mission of tools which help people avoid testing implementation details.

Again, totally up to you. I just want you to know we appreciate all you've done and you're welcome to join us if you like.

**Comment by patrickhulce** [comment]
Ah thanks @kentcdodds that sounds great!

**Comment by patrickhulce** [comment]
Done! 🎉 🍾

**Comment by kentcdodds** [comment]
Perfect!
