### ISSUE TITLE
Support puppeteer v2

### ISSUE THREAD

**Issue by kloy** [testing-library/pptr-testing-library#20]
Puppeteer v2 was recently released. I am not yet aware of what all changes are needed to add support for puppeteer v2.

**Comment by JamesNimlos** [comment]
I just looked into the same thing and I think it's already supported. The [v2 release notes](https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-release-notes) have only one breaking change which was deprecating `page.emulateMedia(type)` in favor of `page.emulateMediaType(type)` and there isn't any reason that would be used in `pptr-testing-library` and I don't find any references to that function. Upgrading has worked so far for us.

**Comment by patrickhulce** [comment]
I believe @JamesNimlos is correct, v2 of puppeteer was a minor API-breaking change (largest actual breaking change IMO was dropping lower node version support, but that doesn't not really affect how we integrate), so you *should* be OK here.
