### ISSUE TITLE
using with typescript

### ISSUE THREAD

**Issue by regikek** [testing-library/pptr-testing-library#35]
when using with typescript, getting a few error:

1) `Cannot redeclare block-scoped variable 'getDocument'. ` multiple tests importing

2) `All files must be modules when the '--isolatedModules' flag is provided.` because im requiring pptr testing library into my tests.

**Comment by patrickhulce** [comment]
Thanks for filing @regikek! Could you be more specific about your setup?

I contribute to a number of typescript repos that use this library without this issue and it sounds more like a test environment configuration problem.

**Comment by regikek** [comment]
yea. im using `playwright-testing-library` which is a fork of this made to play well with playwright.

using jest to run the tests and jest-playwright-preset

here's an example.

```
// errors here.
const { getDocument, queries } = require('playwright-testing-library');
const { getByTestId } = queries
const { getSiteURL } = require('../utils');

describe("Form Tests - all Browsers", () => {
  it("Unable to Submit Empty Form", async () => {
    await page.goto(getSiteURL());

    const document = await getDocument(page);
    const form = await getByTestId(document, 'something')
    expect(form).toBeTruthy();

    await browser.close();
  }, 15000);
});

```

**Comment by patrickhulce** [comment]
ah thanks for the extra detail! that fork has [had significant changes made](https://github.com/testing-library/pptr-testing-library/compare/master...hoverinc:master) to the point where @hoverinc should probably open up issues on their own.

If you're not using this library there's not much we can do for you, sorry :/

Separately @jrolfs if you're interested in committing to maintaining a playwright fork I'm sure we could look into getting it transferred into a official testing-library org if you'd like :)

**Comment by jrolfs** [comment]
@regikek I mirrored this issue over onto the Playwright fork: https://github.com/hoverinc/playwright-testing-library/issues/53

I'll try to look into this week.

**Comment by jrolfs** [comment]
@patrickhulce does your offer to help get playwright-testing-library into @testing-library still stand?

**Comment by patrickhulce** [comment]
Sure thing @jrolfs  I'll ping the right folks in the group to make it happen :)

**Comment by jrolfs** [comment]
Thank you!
