### ISSUE TITLE
Using with typescript <3.8

### ISSUE THREAD

**Issue by martis-git** [testing-library/pptr-testing-library#51]
# `need-more-info`

## Problem
When using in CRA with TS version <3.8, I get the error:
![image](https://user-images.githubusercontent.com/42924400/105635131-72309000-5e72-11eb-97eb-2eb7bde95ef5.png)

## Request
It can be fixed by updating ts to `^3.8`, but **its not obviously**
> I could not find the solution in internet and in `pptr-testing-library` *repo* and *issues*

**If you specify `typescript@^3.8` as requirement before using in `documentation` - it would be awesome!**

> Or refactor d.ts file in more compatable version (without `import type`)

**Comment by martis-git** [comment]
Explicit `exclude: ["node_modules"]` in tsconfig - doesn't help

![image](https://user-images.githubusercontent.com/42924400/105635329-45c94380-5e73-11eb-8b3a-9270e954f87c.png)

**Comment by patrickhulce** [comment]
Thanks for filing @martis-git! It's quite rare in my experience to attempt to typecheck transitive dependencies in node_modules. The `skipLibCheck`  option is practically mandatory in any sizable project I've worked on and that would be my recommendation here (note that `exclude` doesn't prevent a file from being imported into the compilation via an import. It is ONLY a filter on files selected by include)

As for the warning in our repo, I think it'd end up being mostly noise. There's nothing in `pptr-testing-library` that requires typescript 3.8 (the error you're getting is for the `pretty-format` module) and keeping tracking of all our transitive dependencies of any possible version of ts that isn't compatible is rather untenable :/

**Comment by martis-git** [comment]
Thanks for your response

Ok, I got you)

At least, any who'll have the same problem - will can to see this issue during searching :+1:
