### ISSUE TITLE
esbuild is production dependency

### ISSUE THREAD

**Issue by 0xR** [testing-library/pptr-testing-library#59]
esbuild is a production dependency which means that the full esbuild binary of 7.6mb ends up in my deployment artifact. Since I'm running pptr-testing-library in a lambda I want to limit it's size.

**Comment by SevInf** [comment]
@patrickhulce could the fix be published to npm?

**Comment by atabel** [comment]
Please @patrickhulce, can you publish a version with this? I don't want `yarn` to download and build `esbuild` in my projects :(
![image](https://user-images.githubusercontent.com/1849576/144447968-165c29b6-7d19-4dd2-b211-8044a15fb9ec.png)

**Comment by patrickhulce** [comment]
It's been published in v0.7.0
