### ISSUE TITLE
Puppeteer v17 compatibility

### ISSUE THREAD

**Issue by swissspidy** [testing-library/pptr-testing-library#77]
In https://github.com/puppeteer/puppeteer/pull/8844, which was released as part of Puppeteer v17, the execution context has been marked internal, so this access is no longer possible.

I see it's being used twice here:

https://github.com/testing-library/pptr-testing-library/blob/860106be873fa6830c49e529ec1a0b2a65f9bbbd/lib/index.ts#L92

https://github.com/testing-library/pptr-testing-library/blob/860106be873fa6830c49e529ec1a0b2a65f9bbbd/lib/index.ts#L101

**Comment by swissspidy** [comment]
The new recommended approach in v17.1.0 is to use `ElementHandle.frame()` directly, see https://github.com/puppeteer/puppeteer/pull/8875. It should be released soon.

**Comment by patrickhulce** [comment]
Thanks for the note @swissspidy! We'll fix it 👍

**Comment by patrickhulce** [comment]
fix is up at https://github.com/testing-library/pptr-testing-library/pull/78 but getting this to work in a non-breaking way with typescript is...tricky :)

help with tests is welcome

**Comment by patrickhulce** [comment]
fixed by https://github.com/testing-library/pptr-testing-library/pull/78
